### PR TITLE
Fixed $mol_wire implementation

### PR DESCRIPTION
**Pull request by nin-jin**

### CODE REVIEW

**Comment by modderme123** [comment]
Thanks! The other reason mol is disabled is that leaving it enabled makes the benchmark not halt. I wonder if there is some scheduler built into mol that is leaving some promise around?

**Comment by nin-jin** [comment]
Yes, it is used to track the animation frame as first as possible, so that there are no unnecessary recalculations of the layout when the position of the elements is being monitored. I'll think about whether it's possible to make this functionality lazy.

**Comment by nin-jin** [comment]
Made it lazy.

**Comment by modderme123** [comment]
Awesome! I bumped it again (and noticed a slight issue in the esm exports)

**Pull request merged**
